spring:
  profiles:
    active: dev
  sleuth:
    web:
      client:
        enabled: true
    # 采样比例，将多少日志传输给zipkin-server，开发阶段先设置为1.0，即100%
    sampler:
      percentage: 1.0
  zipkin:
    # 也可以不填，默认就是这个
    base-url: http://localhost:9411/